CREATE TABLE ACCOMODATION(
    ACC_ID CHAR(4) NOT NULL,
    ACC_NAME VARCHAR2(30) NOT NULL,
    ACC_ADDR VARCHAR2(100)NOT NULL,
    ACC_TEL VARCHAR2(20) NOT NULL,
    ACC_RATE NUMBER,
    
    CONSTRAINT pk_ACCOMODATION PRIMARY KEY(ACC_ID));

CREATE TABLE REVIEW(
    RES_NO NUMBER(12) NOT NULL,
    CUST_ID VARCHAR2(40) NOT NULL,
    ACC_ID CHAR(4)NOT NULL,
    RATE_TOTAL NUMBER NOT NULL,
    RATE_SERVICE NUMBER,
    RATE_CLEAN NUMBER,
    RATE_CONVINIENT NUMBER,
    
    CONSTRAINT pk_REVIEW PRIMARY KEY(RES_NO),
    CONSTRAINT fk_REVIEW_ACCOMODATION FOREIGN KEY(ACC_ID)
        REFERENCES ACCOMODATION(ACC_ID));