CREATE TABLE MEMBER(
    MEM_ID VARCHAR2(30) NOT NULL,
    MEM_PASS VARCHAR2(30) NOT NULL,
    MEM_NAME VARCHAR2(30) NOT NULL,
    MEM_BIR DATE NOT NULL,
    MEM_NICK VARCHAR2(30) NOT NULL,
    MEM_TEL VARCHAR2(30) NOT NULL,
    MEM_MILEAGE NUMBER DEFAULT 0,
    
    CONSTRAINT pk_MEMBER PRIMARY KEY(MEM_ID));

COMMIT;
CREATE TABLE CORMEMBER(
    COR_NO VARCHAR2(30) NOT NULL,
    COR_ID VARCHAR2(30) NOT NULL,
    COR_PASS VARCHAR2(30) NOT NULL,
    COR_NAME VARCHAR2(30) NOT NULL,
    COR_TEL VARCHAR2(30) NOT NULL,
    
    CONSTRAINT pk_CORMEMBER PRIMARY KEY(COR_NO)
    );
    
CREATE TABLE ACCO(
    ACCO_ID VARCHAR2(10) NOT NULL,
    ACCO_NAME VARCHAR2(30) NOT NULL,
    ACCO_ADD VARCHAR2(100) NOT NULL,
    ACCO_TEL VARCHAR2(30) NOT NULL,
    ACCO_RATE NUMBER,
    ACCO_FACILITY VARCHAR2(1000),
    ACCO_INTRO VARCHAR2(3000),
    COR_NO VARCHAR2(30) NOT NULL,
    
    CONSTRAINT pk_ACCO PRIMARY KEY(ACCO_ID),
    CONSTRAINT fk_ACCO FOREIGN KEY(COR_NO)
        REFERENCES CORMEMBER(COR_NO)
    );
    
COMMIT;

CREATE TABLE ROOM(
    ROOM_ID NUMBER NOT NULL,
    ACCO_ID VARCHAR2(10) NOT NULL,
    ROOM_NAME VARCHAR2(30) NOT NULL,
    ROOM_MAX_PEOPLE NUMBER NOT NULL,
    ROOM_COST NUMBER NOT NULL,
    ROOM_INTRO VARCHAR2(3000),
    ROOM_TOTAL NUMBER NOT NULL,

    CONSTRAINT pk_ROOM PRIMARY KEY(ROOM_ID),
    CONSTRAINT fk_ROOM FOREIGN KEY(ACCO_ID)
        REFERENCES ACCO(ACCO_ID)
    );
    
    
COMMIT;

CREATE TABLE RESERVATION(
    RES_NO NUMBER NOT NULL,
    RES_DATE DATE NOT NULL,
    RES_IN_DATE DATE NOT NULL,
    RES_OUT_DATE DATE NOT NULL,
    RES_PEOPLE NUMBER NOT NULL,
    RES_PRICE NUMBER NOT NULL,
    MEM_ID VARCHAR2(30) NOT NULL,
    ROOM_ID NUMBER NOT NULL,

    CONSTRAINT pk_RES PRIMARY KEY(RES_NO),
    CONSTRAINT fk_RES_MEM FOREIGN KEY(MEM_ID)
        REFERENCES MEMBER(MEM_ID),
    CONSTRAINT fk_RES_ROOM FOREIGN KEY(ROOM_ID)
        REFERENCES ROOM(ROOM_ID)
    );
    
CREATE TABLE REVIEW(    
    RE_TOTAL NUMBER NOT NULL,
    RE_CLEAN NUMBER NOT NULL,
    RE_KIND NUMBER NOT NULL,
    RE_CONVENIENCE NUMBER NOT NULL,
    RE_DETAIL VARCHAR2(3000),
    RES_NO NUMBER NOT NULL,
 
    CONSTRAINT pk_REVIEW PRIMARY KEY(RES_NO),
    CONSTRAINT fk_REVIEW FOREIGN KEY(RES_NO)
        REFERENCES RESERVATION(RES_NO)    
    );
    
CREATE TABLE CANCEL(
    CAN_DATE DATE NOT NULL,
    CAN_REASON VARCHAR2(3000),
    CAN_PRICE NUMBER NOT NULL,
    RES_NO NUMBER NOT NULL,
    
    CONSTRAINT pk_CANCEL PRIMARY KEY(RES_NO),
    CONSTRAINT fk_CANCEL FOREIGN KEY(RES_NO)
        REFERENCES RESERVATION(RES_NO)    
    );
    
    COMMIT;
    
CREATE TABLE ADMIN(
    ADMIN_ID VARCHAR2(30) NOT NULL,
    ADMIN_PASS VARCHAR2(30) NOT NULL,
    
    CONSTRAINT pk_ADMIN PRIMARY KEY(ADMIN_ID)
    );
    
CREATE TABLE EVENT(
    EVE_NO NUMBER NOT NULL,
    EVE_NAME VARCHAR2(100) NOT NULL,
    EVE_START DATE NOT NULL,
    EVE_END DATE NOT NULL,
    EVE_INFO VARCHAR2(3000) NOT NULL,
    EVE_DIS NUMBER NOT NULL,
    
    CONSTRAINT pk_EVENT PRIMARY KEY(EVE_NO)
);